name: Experiment
on:
  push:
    branches: main
    tags: "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  manual:
    name: Experiment
    uses: emacscollective/workflows/.github/workflows/experiment.yml@main
# a
# release
